[project]
name = "auto-vcf-interpretation-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "RetajSWE", email = "retajashaiban@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "crewai>=1.15.15",
    "gradio>=6.24.0",
    "pydantic>=2.12.5",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
    "vcfpy>=0.14.2",
]

[project.scripts]
auto-vcf-interpretation-agent = "auto_vcf_interpretation_agent:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
